from dataclasses import replace
from decimal import Decimal
from pathlib import Path
import json
import tempfile
import unittest
from unittest.mock import Mock

from application.config import ApplicationConfig, ApplicationOverrides
from application.composition_root import create_application_container
from application.quantitative.authority_finalization import QuantitativeAuthorityFinalizationInput
from application.quantitative.state_persistence import authority_fingerprint
from domain.ai.llm_response import LLMResponse
from infrastructure.llm.llm_client import LLMClient
from domain.quantitative.analysis import AnalysisSpecification, ComparisonSpecification, CrossTabAnalysisSpecification, NpsAnalysisSpecification, NumericAnalysisSpecification
from domain.quantitative.analysis_plan import AnalysisExecutionSupport, AnalysisWeightingPolicy, ComparisonResultRoleSelector, PlanVariableBinding, PlannedAnalysis, PlannedComparison
from domain.quantitative.measurement_reconciliation import ReconciliationMatchStatus, ReviewedMeasurementMapping, SemanticHookEquivalenceDecision
from domain.quantitative.questionnaire_authority import AnswerOption, ExpectedVariableBinding, QuestionnaireAuthorshipMode, QuestionnaireQuestion, QuestionnaireQuestionRole, QuestionnaireQuestionType, QuestionnaireSection, ScaleDefinition, ScaleInterpretation
from domain.quantitative.research_design_authority import AnalyticalRequirement, DeliverableRequirement, Hypothesis, HypothesisDirection, MethodologyIntent, QuantitativeResearchQuestion, RequirementObligation, ResearchObjective, ResearchPriority, TargetPopulation
from domain.quantitative.dataset import CodebookVersion, DatasetVersion
from domain.quantitative.insight import QuantitativeInsightGenerationResult
from domain.quantitative.finding import QuantitativeFindingGenerationResult
from domain.quantitative.report import QuantitativeReportCompositionResult
from domain.quantitative.research_question_coverage import QuantitativeAuthorityReference, QuantitativeResearchQuestionCoverageAssessmentVersion, ResearchQuestionAssessmentStatus, ResearchQuestionCoverageDecision
from domain.quantitative.objective_coverage import ObjectiveAssessmentStatus, ObjectiveCoverageDecision, ObjectiveResearchQuestionObligation, ObjectiveResearchQuestionPolicyEdge
from domain.quantitative.study_sufficiency import StudyObjectiveObligation, StudyObjectivePolicyEntry, StudySufficiencyDecision, StudySufficiencyStatus
from domain.quantitative.quality import QualityControlRun
from domain.quantitative.weighting import WeightSet
from infrastructure.persistence.memory.in_memory_project_repository import InMemoryProjectRepository
from infrastructure.persistence.memory.in_memory_quantitative_state_repository import InMemoryQuantitativeStateRepository
from infrastructure.persistence.memory.in_memory_workflow_run_repository import InMemoryWorkflowRunRepository

SAV_BYTES=(Path(__file__).parents[2]/"fixtures"/"quantitative"/"rb_reconciliation.sav").read_bytes()

class _SemanticFake(LLMClient):
    def __init__(self): self.calls=[]
    @staticmethod
    def scalar(value):
        if not isinstance(value,dict): return value
        if value.get("type")=="missing": return None
        raw=value.get("value"); kind=value.get("type")
        return int(raw) if kind in {"integer","int"} else float(raw) if kind in {"decimal","float"} else raw
    def generate(self,prompt,*,options=None):
        prompt=prompt.user if hasattr(prompt,"user") else prompt; self.calls.append(prompt)
        if "AUTHORITATIVE_BUNDLE=" in prompt:
            bundle=json.loads(prompt.split("AUTHORITATIVE_BUNDLE=",1)[1]); proposals=[]
            selected_claims=set()
            for result in bundle["statistical_results"]:
                claim=next((item for item in ("KPI_VALUE","NUMERIC_SUMMARY","DESCRIPTIVE_VALUE") if item in result["allowed_claim_types"]),None)
                if claim=="DESCRIPTIVE_VALUE" and result["display_label"]!="VALID_PERCENTAGE": continue
                if claim is None or claim in selected_claims: continue
                selected_claims.add(claim)
                proposals.append({"claim_type":claim,"finding_text":"The authorized aggregate result is supported.","selected_result_ids":[result["result_id"]],"selected_comparison_ids":[],"limitation_note":"Synthetic aggregate acceptance evidence."})
                if claim=="NUMERIC_SUMMARY": proposals.append(dict(proposals[-1],finding_text="The same authorized numeric result supports a second bounded observation."))
            return LLMResponse(content=json.dumps({"proposals":proposals}),output_tokens=7)
        if "ACCEPTED_FINDINGS=" in prompt:
            findings=json.loads(prompt.split("ACCEPTED_FINDINGS=",1)[1]); contexts={}
            for item in findings: contexts.setdefault(item["analytical_context_fingerprint"],[]).append(item["finding_id"])
            ids=max(contexts.values(),key=len)
            return LLMResponse(content=json.dumps({"proposals":[{"insight_type":"SYNTHESIS","insight_text":"The supported experience and advocacy evidence forms a coherent pattern.","supporting_finding_ids":ids,"referenced_display_values":[],"direction":None,"limitation_note":"Synthetic acceptance synthesis."}]}),output_tokens=7)
        if "APPROVED_SUPPORT=" in prompt:
            support=json.loads(prompt.split("APPROVED_SUPPORT=",1)[1]); insight=support["insights"][0]; by_id={x["finding_id"]:x for x in support["findings"]}; selected=[by_id[x] for x in insight["finding_refs"]]; finding=selected[0]; finding_ids=[x["finding_id"] for x in selected]; result_ids=list(dict.fromkeys(r for x in selected for r in x["result_refs"]))
            section={"section_id":"section-1","section_type":"KEY_FINDINGS","title":"Supported findings","narrative":finding["text"],"finding_refs":finding_ids,"insight_refs":[insight["insight_id"]],"referenced_display_values":[],"authoritative_result_refs":result_ids,"authoritative_table_refs":[],"weighting_status":finding["weighting"],"filter_definition":finding["filter"],"base_definition":finding["base"],"direction":finding["direction"]}
            return LLMResponse(content=json.dumps({"title":"Controlled design-aware report","finding_refs":finding_ids,"insight_refs":[insight["insight_id"]],"sections":[section]}),output_tokens=7)
        raise AssertionError("unexpected semantic boundary")

class Q21211CoherentProductionQuantitativeE2E(unittest.TestCase):
    owner="q2-12-owner"
    def container(self,root,projects,runs,state,llm):
        return create_application_container(config=ApplicationConfig(projects_root=root,persistence_backend="memory",deterministic_stage_executors=False,search_provider="deterministic"),overrides=ApplicationOverrides(llm_client=Mock(),quantitative_llm_client=llm,project_repository=projects,workflow_run_repository=runs,quantitative_state_repository=state))
    def test_one_coherent_production_composed_study(self):
        projects,runs,state=InMemoryProjectRepository(),InMemoryWorkflowRunRepository(),InMemoryQuantitativeStateRepository()
        with tempfile.TemporaryDirectory() as root:
            llm=_SemanticFake(); app=self.container(root,projects,runs,state,llm); ui=app.quantitative_ui_service
            for service in (app.project_service,app.workflow_service,app.quantitative_authority_finalization_service,app.quantitative_objective_coverage_service,app.quantitative_authority_chain_service,app.quantitative_authority_chain_selection_service,app.quantitative_study_sufficiency_service): self.assertIsNotNone(service)
            study=ui.create_study(owner_id=self.owner,title="Controlled consumer study",description="Synthetic design-aware acceptance",submission_key="q2-12-11")
            design_service=app.quantitative_authority_finalization_service._designs
            brief=design_service.create_brief(brief_id="brief",version_id="brief-v1",project_id=study.project_id,run_id=study.run_id,title="Consumer advocacy and experience",business_context="Controlled synthetic category study.",business_problem="Choose a customer strategy.",decision_context="Prioritize experience and advocacy actions.",research_purpose="Measure choice, experience and recommendation.",intended_audience=("Leadership",),target_deliverables=("Report",),constraints=("Synthetic offline data",),provenance="TEST_AUTHORED",created_at="t1",created_by="author")
            brief=design_service.submit_brief_for_review(brief.version_id,project_id=study.project_id,run_id=study.run_id,new_version_id="brief-review",actor_id="reviewer",changed_at="t2")
            brief=design_service.approve_brief(brief.version_id,project_id=study.project_id,run_id=study.run_id,new_version_id="brief-approved",approval_id="brief-approval",expected_fingerprint=brief.fingerprint,actor_id="owner",decided_at="t3",rationale="Approved")
            o1=ResearchObjective("o1","Understand choice and experience.",ResearchPriority.HIGH); o2=ResearchObjective("o2","Understand advocacy and regional variation.",ResearchPriority.MEDIUM)
            rq1=QuantitativeResearchQuestion("rq1","What choices do customers make?",("o1",),"DISTRIBUTION",ResearchPriority.HIGH); rq2=QuantitativeResearchQuestion("rq-shared","How strong are experience and advocacy?",("o1","o2"),"NUMERIC_AND_NPS",ResearchPriority.HIGH); rq3=QuantitativeResearchQuestion("rq2","How do regions differ?",("o2",),"SEGMENTATION",ResearchPriority.MEDIUM)
            reqs=(AnalyticalRequirement("ar-cat","ONE_WAY","Measure categorical choice.",( "o1",),("rq1",),RequirementObligation.MANDATORY),AnalyticalRequirement("ar-rating","NUMERIC","Summarize rating.",( "o1","o2"),("rq-shared",),RequirementObligation.MANDATORY),AnalyticalRequirement("ar-nps","NPS","Measure recommendation NPS.",( "o1","o2"),("rq-shared",),RequirementObligation.MANDATORY),AnalyticalRequirement("ar-cross","CROSS_TAB","Compare choice by segment.",( "o2",),("rq-shared","rq2"),RequirementObligation.OPTIONAL))
            design=design_service.create_design(design_id="design",version_id="design-v1",project_id=study.project_id,run_id=study.run_id,source_brief_version_id=brief.version_id,source_brief_fingerprint=brief.fingerprint,objectives=(o1,o2),research_questions=(rq1,rq2,rq3),hypotheses=(Hypothesis("h1","Choice varies by segment.",( "o1","o2"),("rq1","rq2"),HypothesisDirection.NON_DIRECTIONAL,"DESCRIPTIVE"),),target_population=TargetPopulation(("Synthetic market",),("Adults",),()),methodology_intent=MethodologyIntent("QUANTITATIVE","ONLINE","Controlled sample","TARGET_MARGINS"),analytical_requirements=reqs,deliverable_requirements=(DeliverableRequirement("d1","REPORT","Leadership","en",RequirementObligation.MANDATORY),),assumptions=("Synthetic responses",),limitations=("Acceptance fixture",),created_at="t4",created_by="researcher")
            design=design_service.submit_for_review(design.version_id,project_id=study.project_id,run_id=study.run_id,new_version_id="design-review",actor_id="reviewer",changed_at="t5")
            design=design_service.approve(design.version_id,project_id=study.project_id,run_id=study.run_id,new_version_id="design-approved",approval_id="design-approval",expected_fingerprint=design.fingerprint,actor_id="owner",decided_at="t6",rationale="Approved")
            q_service=app.quantitative_authority_finalization_service._questionnaires; sections=(QuestionnaireSection("main","Main","Core",1),QuestionnaireSection("class","Classification","Cuts",2)); options=lambda p,ls:tuple(AnswerOption(f"{p}-{i}",v,str(i),i) for i,v in enumerate(ls,1)); scale=ScaleDefinition(Decimal("0"),Decimal("10"),tuple((Decimal(i),str(i)) for i in range(11)),ScaleInterpretation.NUMERIC)
            questions=(QuestionnaireQuestion("q-cat","main",QuestionnaireQuestionRole.SUBSTANTIVE,QuestionnaireQuestionType.SINGLE_CHOICE,"Choice?",None,None,("ar-cat",),None,True,options("cat",("Yes","No")),None,(),(),(ExpectedVariableBinding("ev-cat","categorical"),),True,1,"team"),QuestionnaireQuestion("q-rating","main",QuestionnaireQuestionRole.SUBSTANTIVE,QuestionnaireQuestionType.NUMERIC,"Rating?",None,None,("ar-rating",),None,True,(),None,(),(("minimum","0"),("maximum","10")),(ExpectedVariableBinding("ev-rating","numeric"),),True,2,"team"),QuestionnaireQuestion("q-nps","main",QuestionnaireQuestionRole.SUBSTANTIVE,QuestionnaireQuestionType.NPS,"Recommend?",None,None,("ar-nps",),None,True,(),scale,(),(),(ExpectedVariableBinding("ev-nps","nps"),),True,3,"team"),QuestionnaireQuestion("q-sex","class",QuestionnaireQuestionRole.DEMOGRAPHIC,QuestionnaireQuestionType.SINGLE_CHOICE,"Classification",None,None,(),"Weighting and cut",True,options("sex",("Group A","Group B")),None,(),(),(ExpectedVariableBinding("ev-sex","sex"),),False,1,"team"),QuestionnaireQuestion("q-region","class",QuestionnaireQuestionRole.SUBSTANTIVE,QuestionnaireQuestionType.SINGLE_CHOICE,"Region",None,None,("ar-cross",),None,True,options("region",("West","Center","East")),None,(),(),(ExpectedVariableBinding("ev-region","region"),),False,2,"team"))
            q=q_service.create_draft(questionnaire_id="questionnaire",version_id="q-v1",project_id=study.project_id,run_id=study.run_id,research_design_version_id=design.version_id,research_design_fingerprint=design.fingerprint,title="Controlled questionnaire",purpose="Measure approved requirements",language="en",sections=sections,questions=questions,routing_rules=(),provenance="TEST_AUTHORED",authorship_mode=QuestionnaireAuthorshipMode.INTERNAL_HUMAN,estimated_interview_length_minutes=4,assumptions=(),limitations=(),created_at="t7",created_by="researcher")
            q=q_service.submit_for_review(q.version_id,project_id=study.project_id,run_id=study.run_id,new_version_id="q-review",actor_id="reviewer",changed_at="t8"); q=q_service.approve(q.version_id,project_id=study.project_id,run_id=study.run_id,new_version_id="q-approved",approval_id="q-approval",expected_fingerprint=q.fingerprint,expected_validation_fingerprint=q.validation_manifest_fingerprint,expected_coverage_fingerprint=q.coverage_manifest_fingerprint,actor_id="owner",decided_at="t9",rationale="Approved")
            study=ui.upload(study.study_id,owner_id=self.owner,filename="controlled.sav",content=SAV_BYTES); dataset=ui.state.load(study.dataset_record_id,project_id=study.project_id,expected_type=DatasetVersion); codebook=ui.state.load(study.codebook_record_id,project_id=study.project_id,expected_type=CodebookVersion)
            study=ui.run_default_qc(study.study_id,owner_id=self.owner); qc=ui.state.load(study.qc_record_id,project_id=study.project_id,expected_type=QualityControlRun); study=ui.approve_qc(study.study_id,owner_id=self.owner,actor_id="owner",fingerprint=qc.fingerprint,decision="APPROVED",rationale="Approved")
            study=ui.construct_weights_from_payload(study.study_id,owner_id=self.owner,targets={"sex":{"Group A":50,"Group B":50}}); weights=ui.state.load(study.weight_set_record_id,project_id=study.project_id,expected_type=WeightSet); study=ui.approve_weights(study.study_id,owner_id=self.owner,actor_id="owner",fingerprint=weights.reproducibility_fingerprint,decision="APPROVED",rationale="Approved")
            rb=app.quantitative_authority_finalization_service._reconciliations; candidate=rb.create(reconciliation_id="rb",version_id="rb-candidate",project_id=study.project_id,run_id=study.run_id,dataset=dataset,codebook=codebook,created_at="t10",created_by="system"); schema=q_service.derive_expected_measurement_schema(q.version_id,project_id=study.project_id); expected={x.expected_variable_id:x for x in schema.variables}; actual={x.variable_id:x for x in codebook.variables}; mappings=[]
            self.assertEqual(ReconciliationMatchStatus.REQUIRES_REVIEW,next(x for x in candidate.variable_outcomes if x.expected_variable_id=="ev-nps").status)
            for outcome in candidate.variable_outcomes:
                e=expected[outcome.expected_variable_id]; a=actual[outcome.actual_variable_id]; codes=tuple((str(code),str(code)) for code,_ in e.value_labels); mapping=ReviewedMeasurementMapping("map-"+e.expected_variable_id,e.expected_variable_id,e.fingerprint,a.variable_id,a.fingerprint,codes,(("9","9"),) if e.expected_variable_id=="ev-cat" else (),codes,(),"owner","Reviewed","t11","base-"+e.expected_variable_id)
                if e.expected_variable_id=="ev-nps": mapping=rb.review_semantic_hook_equivalence(candidate_version_id=candidate.version_id,project_id=study.project_id,run_id=study.run_id,dataset=dataset,codebook=codebook,expected_variable_id=e.expected_variable_id,actual_variable_id=a.variable_id,expected_semantic_hook="NPS_SOURCE_0_10",decision=SemanticHookEquivalenceDecision.APPROVE_EQUIVALENCE,actor_id="owner",decided_at="t11",rationale="Exact imported 0-10 NPS source",decision_id="nps-hook",base_mapping=mapping)
                mappings.append(mapping)
            reviewed=rb.create(reconciliation_id="rb",version_id="rb-reviewed",project_id=study.project_id,run_id=study.run_id,dataset=dataset,codebook=codebook,created_at="t12",created_by="owner",reviewed_mappings=tuple(mappings),parent_version_id=candidate.version_id); accepted=rb.approve(reviewed.version_id,project_id=study.project_id,run_id=study.run_id,approval_id="rb-approval",expected_fingerprint=reviewed.fingerprint,actor_id="owner",decided_at="t13",rationale="Approved",dataset=dataset,codebook=codebook)
            bindings={x.expected_variable_id:PlanVariableBinding(x.expected_variable_id,x.actual_variable_id,x.actual_variable_fingerprint) for x in accepted.variable_outcomes}; aid=lambda x:bindings[x].actual_variable_id
            analyses=(PlannedAnalysis("pa-cat",AnalysisSpecification("spec-cat",aid("ev-cat")),"",("o1",),("rq1",),("ar-cat",),(bindings["ev-cat"],),"TOTAL_DISTRIBUTION","MANDATORY",AnalysisWeightingPolicy.UNWEIGHTED,None,None,(),(),AnalysisExecutionSupport.SUPPORTED),PlannedAnalysis("pa-rating",NumericAnalysisSpecification("spec-rating",aid("ev-rating")),"",("o1","o2"),("rq-shared",),("ar-rating",),(bindings["ev-rating"],),"NUMERIC_SUMMARY","MANDATORY",AnalysisWeightingPolicy.UNWEIGHTED,None,None,(),(),AnalysisExecutionSupport.SUPPORTED),PlannedAnalysis("pa-nps",NpsAnalysisSpecification("spec-nps",aid("ev-nps")),"",("o1","o2"),("rq-shared",),("ar-nps",),(bindings["ev-nps"],),"NPS","MANDATORY",AnalysisWeightingPolicy.UNWEIGHTED,None,None,(),(),AnalysisExecutionSupport.SUPPORTED),PlannedAnalysis("pa-cross",CrossTabAnalysisSpecification(specification_id="spec-cross",variable_id=aid("ev-cat"),column_variable_id=aid("ev-sex")),"",("o2",),("rq-shared","rq2"),("ar-cross",),(bindings["ev-cat"],bindings["ev-sex"]),"CROSS_TAB","OPTIONAL",AnalysisWeightingPolicy.UNWEIGHTED,None,None,(),(),AnalysisExecutionSupport.SUPPORTED))
            comparison=PlannedComparison("pc-cross",ComparisonSpecification("cmp-cross","INDEPENDENT_TWO_PROPORTION_Z_TEST",aid("ev-cat"),aid("ev-sex"),1.0,2.0,1.0),"",("pa-cross",),("rq-shared","rq2"),("ar-cross",),"SIGNIFICANCE",(),(),(ComparisonResultRoleSelector("GROUP_A","pa-cross","CROSS_TAB_COLUMN_PERCENTAGE",aid("ev-cat"),aid("ev-sex"),1.0,1.0,"ALL_ROWS"),ComparisonResultRoleSelector("GROUP_B","pa-cross","CROSS_TAB_COLUMN_PERCENTAGE",aid("ev-cat"),aid("ev-sex"),1.0,2.0,"ALL_ROWS")),("o2",),"OPTIONAL")
            rc=app.quantitative_authority_finalization_service._plans; plan=rc.create_draft(plan_id="plan",version_id="plan-v1",project_id=study.project_id,run_id=study.run_id,dataset=dataset,codebook=codebook,planned_analyses=analyses,planned_comparisons=(comparison,),created_at="t14",created_by="researcher"); plan=rc.submit_for_review(plan.version_id,project_id=study.project_id,run_id=study.run_id,new_version_id="plan-review",actor_id="reviewer",changed_at="t15"); plan=rc.approve(plan.version_id,project_id=study.project_id,run_id=study.run_id,new_version_id="plan-approved",approval_id="plan-approval",expected_fingerprint=plan.fingerprint,actor_id="owner",decided_at="t16",rationale="Approved",dataset=dataset,codebook=codebook)
            completed=ui.activate_design_aware_workflow(study.study_id,owner_id=self.owner)
            self.assertEqual("COMPLETED",completed.state); safe=app.workflow_service.get_task_results(study.run_id)["quantitative"]
            self.assertEqual("DESIGN_AWARE_EXECUTION",safe["analysis_execution_mode"]); self.assertEqual(3,len(llm.calls)); self.assertIn("report_lineage_manifest_record_id",safe); self.assertIn("rq_coverage_manifest_record_id",safe)
            rh=app.quantitative_objective_coverage_service._questions
            assessments={x.research_question_id:x for x in ui.state.list_for_run(study.run_id,project_id=study.project_id,expected_type=QuantitativeResearchQuestionCoverageAssessmentVersion)}
            finding_generation=ui.state.load(safe["finding_generation_record_id"],project_id=study.project_id,expected_type=QuantitativeFindingGenerationResult)
            self.assertEqual({"rq1","rq-shared","rq2"},set(assessments))
            self.assertEqual(ResearchQuestionAssessmentStatus.INCONCLUSIVE,assessments["rq2"].status)
            shared=assessments["rq-shared"]; self.assertEqual(("ar-nps","ar-rating"),shared.mandatory_requirement_ids); self.assertEqual(("ar-cross",),shared.optional_requirement_ids)
            self.assertIn(shared.status,{ResearchQuestionAssessmentStatus.READY_FOR_SUFFICIENCY_REVIEW,ResearchQuestionAssessmentStatus.REQUIRES_METHODOLOGICAL_REVIEW}); self.assertNotEqual(ResearchQuestionAssessmentStatus.BLOCKED,shared.status)
            rh_projections={}
            for rq_id in ("rq1","rq-shared"):
                value=assessments[rq_id]; self.assertIn(value.status,{ResearchQuestionAssessmentStatus.READY_FOR_SUFFICIENCY_REVIEW,ResearchQuestionAssessmentStatus.REQUIRES_METHODOLOGICAL_REVIEW},msg=(tuple(x.reason for x in finding_generation.rejected_findings),{k:(v.status.value,tuple((r.analytical_requirement_id,r.status.value,r.reason_codes) for r in v.requirement_assessments)) for k,v in assessments.items()}))
                rh.approve(value.version_id,project_id=study.project_id,run_id=study.run_id,new_version_id=f"rh-{rq_id}-approved",approval_id=f"rh-{rq_id}-approval",expected_fingerprint=value.fingerprint,decision="SUFFICIENTLY_ANSWERED",actor_id="human",decided_at="t17",rationale="Mandatory evidence is sufficient.")
                rh_projections[rq_id]=rh.resolve_current_approved(project_id=study.project_id,run_id=study.run_id,research_question_id=rq_id)
            ri=app.quantitative_objective_coverage_service
            edges=(ObjectiveResearchQuestionPolicyEdge("o1","rq1",ObjectiveResearchQuestionObligation.MANDATORY,"Required"),ObjectiveResearchQuestionPolicyEdge("o1","rq-shared",ObjectiveResearchQuestionObligation.MANDATORY,"Required shared"),ObjectiveResearchQuestionPolicyEdge("o2","rq-shared",ObjectiveResearchQuestionObligation.MANDATORY,"Required shared"),ObjectiveResearchQuestionPolicyEdge("o2","rq2",ObjectiveResearchQuestionObligation.OPTIONAL,"Optional segmentation"))
            policy=ri.create_policy(policy_id="ri-policy",version_id="ri-policy-draft",project_id=study.project_id,run_id=study.run_id,design=design,edges=edges,created_at="t18",created_by="human")
            policy=ri.submit_policy_for_review(policy.version_id,project_id=study.project_id,run_id=study.run_id,new_version_id="ri-policy-review",actor_id="human",changed_at="t19")
            policy=ri.approve_policy(policy.version_id,project_id=study.project_id,run_id=study.run_id,new_version_id="ri-policy-approved",approval_id="ri-policy-approval",expected_fingerprint=policy.fingerprint,actor_id="human",decided_at="t20",rationale="Approved objective policy",current_design=design)
            policy_approval=ri.repository.get_policy_approval("ri-policy-approval",project_id=study.project_id)
            ri_projections={}
            for objective_id,authorities in (("o1",(rh_projections["rq1"],rh_projections["rq-shared"])),("o2",(rh_projections["rq-shared"],))):
                value=ri.assess_objective(project_id=study.project_id,run_id=study.run_id,design=design,objective_id=objective_id,policy=policy,policy_approval=policy_approval,research_question_authorities=authorities,created_at="t21",created_by="system")
                if objective_id=="o2": self.assertEqual(("rq-shared",),value.mandatory_research_question_ids); self.assertEqual(("rq2",),value.optional_research_question_ids)
                ri.approve_objective(value.version_id,project_id=study.project_id,run_id=study.run_id,new_version_id=f"ri-{objective_id}-approved",approval_id=f"ri-{objective_id}-approval",expected_fingerprint=value.fingerprint,decision=ObjectiveCoverageDecision.OBJECTIVE_SATISFIED,actor_id="human",decided_at="t22",rationale="Objective evidence is sufficient",current_design=design)
                ri_projections[objective_id]=ri.resolve_current_approved_objective(project_id=study.project_id,run_id=study.run_id,objective_id=objective_id,design=design,policy=policy,research_question_authorities=authorities)[0]
            self.assertEqual({"o1","o2"},set(ri_projections))
            def ref(kind,value,identity): return QuantitativeAuthorityReference(kind,getattr(value,identity),authority_fingerprint(value))
            rd=ui.state.load(safe["analysis_execution_manifest_record_id"],project_id=study.project_id); rd_coverage=ui.state.load(rd.coverage_manifest_id,project_id=study.project_id)
            re_input=ui.state.load(safe["finding_input_authority_record_id"],project_id=study.project_id); re_lineage=ui.state.load(safe["finding_lineage_manifest_record_id"],project_id=study.project_id); re_coverage=ui.state.load(safe["finding_coverage_manifest_record_id"],project_id=study.project_id)
            rf_input=ui.state.load(safe["insight_input_authority_record_id"],project_id=study.project_id); rf_lineage=ui.state.load(safe["insight_lineage_manifest_record_id"],project_id=study.project_id); rf_coverage=ui.state.load(safe["insight_coverage_manifest_record_id"],project_id=study.project_id)
            rg_input=ui.state.load(safe["report_input_authority_record_id"],project_id=study.project_id); rg_lineage=ui.state.load(safe["report_lineage_manifest_record_id"],project_id=study.project_id); rg_coverage=ui.state.load(safe["report_coverage_manifest_record_id"],project_id=study.project_id)
            qc_approval=ui.state.load(study.qc_approval_id,project_id=study.project_id); rh_refs=[]
            for rq_id in ("rq1","rq-shared"):
                projection=rh_projections[rq_id]; assessment=ui.state.load(projection.assessment_version_id,project_id=study.project_id); approval=rh.repository.get_approval(projection.approval_id,project_id=study.project_id)
                rh_refs.extend((ref("RH_ASSESSMENT",assessment,"version_id"),ref("RH_APPROVAL",approval,"approval_id")))
            ri_refs=[]
            for objective_id in ("o1","o2"):
                assessment,approval=ri.resolve_current_approved_objective(project_id=study.project_id,run_id=study.run_id,objective_id=objective_id)
                self.assertEqual(assessment.fingerprint,approval.assessment_fingerprint)
                ri_refs.append(ref("RI_OBJECTIVE",assessment,"version_id"))
            request=QuantitativeAuthorityFinalizationInput(project_id=study.project_id,run_id=study.run_id,terminal_result_record_id=completed.terminal_result_record_id,source_brief=ref("QZ_BRIEF",brief,"version_id"),research_design=ref("QZ_DESIGN",design,"version_id"),questionnaire=ref("RA_QUESTIONNAIRE",q,"version_id"),reconciliation=ref("RB_RECONCILIATION",accepted,"version_id"),analysis_plan=ref("RC_PLAN",plan,"version_id"),analysis_execution=(ref("RD_MANIFEST",rd,"manifest_id"),ref("RD_COVERAGE",rd_coverage,"coverage_id")),finding_authority=(ref("RE_INPUT",re_input,"authority_id"),ref("RE_LINEAGE",re_lineage,"manifest_id"),ref("RE_COVERAGE",re_coverage,"coverage_id")),insight_authority=(ref("RF_INPUT",rf_input,"authority_id"),ref("RF_LINEAGE",rf_lineage,"manifest_id"),ref("RF_COVERAGE",rf_coverage,"coverage_id")),report_authority=(ref("RG_INPUT",rg_input,"authority_id"),ref("RG_LINEAGE",rg_lineage,"manifest_id"),ref("RG_COVERAGE",rg_coverage,"coverage_id")),research_question_authorities=tuple(rh_refs),objective_authorities=tuple(ri_refs),dataset=QuantitativeAuthorityReference("DATASET",safe["dataset_record_id"],authority_fingerprint(dataset)),codebook=QuantitativeAuthorityReference("CODEBOOK",safe["codebook_record_id"],authority_fingerprint(codebook)),qc_authority=ref("QC_APPROVAL",qc_approval,"approval_id"),weight_set_authorities=(QuantitativeAuthorityReference("WEIGHT_SET",safe["weight_set_record_id"],authority_fingerprint(weights)),))
            rl=app.quantitative_authority_finalization_service; finalized=rl.finalize(request,created_at="t23",created_by="system"); current=rl.resolve_current(project_id=study.project_id,run_id=study.run_id); self.assertEqual(finalized,current)
            self.assertEqual(finalized,rl.finalize(request,created_at="t23",created_by="system"))
            forward=app.quantitative_authority_chain_service.reconstruct_forward(manifest_id=finalized.manifest_id,project_id=study.project_id,run_id=study.run_id); backward=app.quantitative_authority_chain_service.reconstruct_backward(manifest_id=finalized.manifest_id,objective_authority_id=ri_refs[0].authority_id,project_id=study.project_id,run_id=study.run_id); self.assertEqual(forward,backward)
            rj=app.quantitative_study_sufficiency_service
            study_policy=rj.create_policy(policy_id="rj-policy",version_id="rj-policy-draft",project_id=study.project_id,run_id=study.run_id,entries=(StudyObjectivePolicyEntry("o1",StudyObjectiveObligation.MANDATORY,"Primary objective"),StudyObjectivePolicyEntry("o2",StudyObjectiveObligation.MANDATORY,"Secondary objective")),created_at="t24",created_by="human")
            study_policy=rj.submit_policy_for_review(study_policy.version_id,project_id=study.project_id,run_id=study.run_id,new_version_id="rj-policy-review",actor_id="human",changed_at="t25"); study_policy=rj.approve_policy(study_policy.version_id,project_id=study.project_id,run_id=study.run_id,new_version_id="rj-policy-approved",approval_id="rj-policy-approval",expected_fingerprint=study_policy.fingerprint,actor_id="human",decided_at="t26",rationale="Approved study policy")
            study_assessment=rj.assess_current_study(project_id=study.project_id,run_id=study.run_id,created_at="t27",created_by="system"); self.assertEqual(StudySufficiencyStatus.READY_FOR_STUDY_REVIEW,study_assessment.status)
            rj.approve_study(study_assessment.version_id,project_id=study.project_id,run_id=study.run_id,new_version_id="rj-approved",approval_id="rj-approval",expected_fingerprint=study_assessment.fingerprint,decision=StudySufficiencyDecision.STUDY_SUFFICIENT,actor_id="human",decided_at="t28",rationale="Mandatory objective evidence is sufficient")
            study_projection=rj.get_approved_projection(project_id=study.project_id,run_id=study.run_id); self.assertEqual(StudySufficiencyDecision.STUDY_SUFFICIENT,study_projection.decision); self.assertEqual(3,len(llm.calls))
            self.assertEqual((finalized.manifest_id,finalized.manifest_fingerprint),(study_projection.manifest_id,study_projection.manifest_fingerprint))
            self.assertEqual({"o1","o2"},{item.objective_id for item in study_projection.mandatory_objective_references})
            self.assertEqual(2,len(design.objectives)); self.assertEqual({"o1","o2"},set(rq2.objective_ids)); self.assertEqual({"ar-rating","ar-nps","ar-cross"},{item.requirement_id for item in reqs if "rq-shared" in item.research_question_ids})
            baseline=(brief.version_id,brief.fingerprint,design.version_id,design.fingerprint,q.version_id,q.fingerprint,dataset.version_id,dataset.dataset_fingerprint,codebook.codebook_version_id,codebook.fingerprint,accepted.version_id,accepted.fingerprint,plan.version_id,plan.fingerprint,rd.manifest_id,rd.fingerprint,re_lineage.manifest_id,re_lineage.fingerprint,rf_lineage.manifest_id,rf_lineage.fingerprint,rg_lineage.manifest_id,rg_lineage.fingerprint,finalized.manifest_id,finalized.manifest_fingerprint,finalized.selection_id,finalized.selection_fingerprint,study_projection.assessment_version_id,study_projection.assessment_fingerprint,study_projection.approval_id,study_projection.approval_fingerprint)
            historical_study_projection=study_projection
            superseded_policy=rj.supersede_policy(study_policy.version_id,project_id=study.project_id,run_id=study.run_id,new_version_id="rj-policy-superseded",actor_id="human",changed_at="t28a")
            optional_policy=rj.create_policy(policy_id="rj-policy",version_id="rj-policy-optional-draft",project_id=study.project_id,run_id=study.run_id,entries=(StudyObjectivePolicyEntry("o1",StudyObjectiveObligation.MANDATORY,"Primary objective"),StudyObjectivePolicyEntry("o2",StudyObjectiveObligation.OPTIONAL,"Secondary objective")),created_at="t28b",created_by="human",version_sequence=superseded_policy.version_sequence+1,parent_version_id=superseded_policy.version_id)
            optional_policy=rj.submit_policy_for_review(optional_policy.version_id,project_id=study.project_id,run_id=study.run_id,new_version_id="rj-policy-optional-review",actor_id="human",changed_at="t28c")
            optional_policy=rj.approve_policy(optional_policy.version_id,project_id=study.project_id,run_id=study.run_id,new_version_id="rj-policy-optional-approved",approval_id="rj-policy-optional-approval",expected_fingerprint=optional_policy.fingerprint,actor_id="human",decided_at="t28d",rationale="Approved optional Objective policy")
            optional_assessment=rj.assess_current_study(project_id=study.project_id,run_id=study.run_id,created_at="t28e",created_by="system"); self.assertEqual(StudySufficiencyStatus.READY_FOR_STUDY_REVIEW,optional_assessment.status)
            self.assertEqual(optional_assessment,rj.assess_current_study(project_id=study.project_id,run_id=study.run_id,created_at="t28e",created_by="system"))
            self.assertEqual(("o1",),optional_assessment.mandatory_objective_ids); self.assertEqual(("o2",),optional_assessment.optional_objective_ids)
            rj.approve_study(optional_assessment.version_id,project_id=study.project_id,run_id=study.run_id,new_version_id="rj-optional-approved",approval_id="rj-optional-approval",expected_fingerprint=optional_assessment.fingerprint,decision=StudySufficiencyDecision.STUDY_SUFFICIENT,actor_id="human",decided_at="t28f",rationale="Mandatory Objective remains sufficient")
            study_projection=rj.get_approved_projection(project_id=study.project_id,run_id=study.run_id); self.assertEqual(StudySufficiencyDecision.STUDY_SUFFICIENT,study_projection.decision)
            self.assertEqual(("o1",),tuple(x.objective_id for x in study_projection.mandatory_objective_references)); self.assertEqual(("o2",),tuple(x.objective_id for x in study_projection.optional_objective_references))
            self.assertIsNotNone(rj.repository.get_assessment(historical_study_projection.assessment_version_id,project_id=study.project_id)); self.assertIsNotNone(rj.repository.get_approval(historical_study_projection.approval_id,project_id=study.project_id))
            ra_coverage=q_service.derive_coverage_manifest(q.version_id,project_id=study.project_id); rb_availability=rb._repository.get_availability(accepted.data_availability_manifest_id,project_id=study.project_id); rc_coverage=rc._repository.get_coverage(plan.coverage_manifest_id,project_id=study.project_id)
            def replace_rh(tag,decisions):
                values=rh.assess(project_id=study.project_id,run_id=study.run_id,design=design,questionnaire_coverage=ra_coverage,data_availability=rb_availability,plan=plan,plan_coverage=rc_coverage,execution_manifest=rd,execution_coverage=rd_coverage,finding_coverage=re_coverage,insight_coverage=rf_coverage,report_coverage=rg_coverage,finding_lineage=re_lineage,insight_lineage=rf_lineage,report_lineage=rg_lineage,created_at=f"t-{tag}",created_by="system",version_sequence=tag)
                projections={}
                for value in values:
                    decision=decisions.get(value.research_question_id,ResearchQuestionCoverageDecision.INCONCLUSIVE)
                    rh.approve(value.version_id,project_id=study.project_id,run_id=study.run_id,new_version_id=f"rh-{tag}-{value.research_question_id}-approved",approval_id=f"rh-{tag}-{value.research_question_id}-approval",expected_fingerprint=value.fingerprint,decision=decision,actor_id="human",decided_at=f"t-{tag}-approval",rationale="Reviewed coherent evidence outcome.")
                    projections[value.research_question_id]=rh.resolve_current_approved(project_id=study.project_id,run_id=study.run_id,research_question_id=value.research_question_id)
                return projections
            last_o1_version=ri_projections["o1"].version_id
            def replace_o1(tag,authorities,decision,expected_status):
                nonlocal last_o1_version
                value=ri.assess_objective(project_id=study.project_id,run_id=study.run_id,design=design,objective_id="o1",policy=policy,policy_approval=policy_approval,research_question_authorities=authorities,created_at=f"t-{tag}",created_by="system",version_sequence=tag,parent_version_id=last_o1_version)
                self.assertEqual(expected_status,value.status)
                ri.approve_objective(value.version_id,project_id=study.project_id,run_id=study.run_id,new_version_id=f"ri-o1-{tag}-approved",approval_id=f"ri-o1-{tag}-approval",expected_fingerprint=value.fingerprint,decision=decision,actor_id="human",decided_at=f"t-{tag}-approval",rationale="Reviewed Objective outcome.",current_design=design)
                projection=ri.get_approved_projection(project_id=study.project_id,run_id=study.run_id,objective_id="o1"); last_o1_version=projection.assessment_version_id; return projection
            def replace_rj_policy_and_assess(tag,expected_status,decision):
                nonlocal optional_policy
                marker=rj.supersede_policy(optional_policy.version_id,project_id=study.project_id,run_id=study.run_id,new_version_id=f"rj-{tag}-superseded",actor_id="human",changed_at=f"t-{tag}-s")
                optional_policy=rj.create_policy(policy_id="rj-policy",version_id=f"rj-{tag}-draft",project_id=study.project_id,run_id=study.run_id,entries=(StudyObjectivePolicyEntry("o1",StudyObjectiveObligation.MANDATORY,"Primary objective"),StudyObjectivePolicyEntry("o2",StudyObjectiveObligation.OPTIONAL,"Secondary objective")),created_at=f"t-{tag}-d",created_by="human",version_sequence=marker.version_sequence+1,parent_version_id=marker.version_id)
                optional_policy=rj.submit_policy_for_review(optional_policy.version_id,project_id=study.project_id,run_id=study.run_id,new_version_id=f"rj-{tag}-review",actor_id="human",changed_at=f"t-{tag}-r")
                optional_policy=rj.approve_policy(optional_policy.version_id,project_id=study.project_id,run_id=study.run_id,new_version_id=f"rj-{tag}-approved-policy",approval_id=f"rj-{tag}-policy-approval",expected_fingerprint=optional_policy.fingerprint,actor_id="human",decided_at=f"t-{tag}-pa",rationale="Approved outcome policy")
                value=rj.assess_current_study(project_id=study.project_id,run_id=study.run_id,created_at=f"t-{tag}-a",created_by="system"); self.assertEqual(expected_status,value.status)
                rj.approve_study(value.version_id,project_id=study.project_id,run_id=study.run_id,new_version_id=f"rj-{tag}-approved",approval_id=f"rj-{tag}-approval",expected_fingerprint=value.fingerprint,decision=decision,actor_id="human",decided_at=f"t-{tag}-ha",rationale="Reviewed deterministic Study outcome")
                return rj.get_approved_projection(project_id=study.project_id,run_id=study.run_id)
            partial_o1=replace_o1(40,(rh_projections["rq1"],rh_projections["rq-shared"]),ObjectiveCoverageDecision.OBJECTIVE_PARTIALLY_SATISFIED,ObjectiveAssessmentStatus.READY_FOR_OBJECTIVE_REVIEW)
            partial_study=replace_rj_policy_and_assess(40,StudySufficiencyStatus.PARTIALLY_SUPPORTED,StudySufficiencyDecision.STUDY_PARTIALLY_SUFFICIENT); self.assertEqual(ObjectiveCoverageDecision.OBJECTIVE_PARTIALLY_SATISFIED,partial_o1.decision)
            inconclusive_rh=replace_rh(50,{"rq1":ResearchQuestionCoverageDecision.INCONCLUSIVE,"rq-shared":ResearchQuestionCoverageDecision.INCONCLUSIVE})
            inconclusive_o1=replace_o1(50,(inconclusive_rh["rq1"],inconclusive_rh["rq-shared"]),ObjectiveCoverageDecision.OBJECTIVE_INCONCLUSIVE,ObjectiveAssessmentStatus.INCONCLUSIVE)
            inconclusive_study=replace_rj_policy_and_assess(50,StudySufficiencyStatus.INCONCLUSIVE,StudySufficiencyDecision.STUDY_INCONCLUSIVE); self.assertEqual(ObjectiveCoverageDecision.OBJECTIVE_INCONCLUSIVE,inconclusive_o1.decision)
            unanswered_rh=replace_rh(60,{"rq1":ResearchQuestionCoverageDecision.NOT_ANSWERED,"rq-shared":ResearchQuestionCoverageDecision.NOT_ANSWERED})
            insufficient_o1=replace_o1(60,(unanswered_rh["rq1"],unanswered_rh["rq-shared"]),ObjectiveCoverageDecision.OBJECTIVE_NOT_SATISFIED,ObjectiveAssessmentStatus.NOT_SATISFIED)
            insufficient_study=replace_rj_policy_and_assess(60,StudySufficiencyStatus.NOT_SUFFICIENT,StudySufficiencyDecision.STUDY_NOT_SUFFICIENT); self.assertEqual(ObjectiveCoverageDecision.OBJECTIVE_NOT_SATISFIED,insufficient_o1.decision)
            self.assertEqual({StudySufficiencyDecision.STUDY_PARTIALLY_SUFFICIENT,StudySufficiencyDecision.STUDY_INCONCLUSIVE,StudySufficiencyDecision.STUDY_NOT_SUFFICIENT},{partial_study.decision,inconclusive_study.decision,insufficient_study.decision})
            study_projection=insufficient_study
            self.assertEqual(ResearchQuestionAssessmentStatus.INCONCLUSIVE,assessments["rq2"].status); self.assertIsNotNone(rg_lineage)
            dataset_only=(design_service.resolve_dataset_only(authority_id="dataset-only-qz",project_id=study.project_id,run_id="dataset-only-run"),q_service.resolve_dataset_only(authority_id="dataset-only-ra",project_id=study.project_id,run_id="dataset-only-run"),rb.resolve_dataset_only(authority_id="dataset-only-rb",project_id=study.project_id,run_id="dataset-only-run"),rc.resolve_dataset_only(authority_id="dataset-only-rc",project_id=study.project_id,run_id="dataset-only-run"),rh.dataset_only_absence(project_id=study.project_id,run_id="dataset-only-run"),ri.dataset_only_absence(project_id=study.project_id,run_id="dataset-only-run"),rj.dataset_only_absence(project_id=study.project_id,run_id="dataset-only-run"))
            for absence in dataset_only: self.assertIn("NO_",repr(absence)); self.assertNotIn("objective_id='",repr(absence).lower())
            with self.assertRaises(Exception): app.quantitative_authority_chain_selection_service.resolve_current_authority_chain(project_id=study.project_id,run_id=study.run_id,execution_mode="DATASET_ONLY_EXPLORATORY_EXECUTION")
            exploratory=ui.create_study(owner_id=self.owner,title="Dataset-only control",description="Synthetic exploratory separation",submission_key="q2-12-11-dataset-only")
            exploratory=ui.upload(exploratory.study_id,owner_id=self.owner,filename="exploratory.sav",content=SAV_BYTES); exploratory=ui.run_default_qc(exploratory.study_id,owner_id=self.owner); exploratory_qc=ui.state.load(exploratory.qc_record_id,project_id=exploratory.project_id,expected_type=QualityControlRun); exploratory=ui.approve_qc(exploratory.study_id,owner_id=self.owner,actor_id="owner",fingerprint=exploratory_qc.fingerprint,decision="APPROVED",rationale="Approved exploratory QC")
            exploratory=ui.construct_weights_from_payload(exploratory.study_id,owner_id=self.owner,targets={"sex":{"Group A":50,"Group B":50}}); exploratory_weights=ui.state.load(exploratory.weight_set_record_id,project_id=exploratory.project_id,expected_type=WeightSet); exploratory=ui.approve_weights(exploratory.study_id,owner_id=self.owner,actor_id="owner",fingerprint=exploratory_weights.reproducibility_fingerprint,decision="APPROVED",rationale="Approved exploratory weights")
            exploratory=ui.resume_workflow(exploratory.study_id,owner_id=self.owner); exploratory_safe=app.workflow_service.get_task_results(exploratory.run_id)["quantitative"]
            self.assertEqual("COMPLETED",exploratory.state); self.assertEqual("DATASET_ONLY_EXPLORATORY_EXECUTION",exploratory_safe["analysis_execution_mode"]); self.assertNotIn("analysis_plan_version_id",exploratory_safe); self.assertIn("rq_coverage_absence_record_id",exploratory_safe)
            with self.assertRaises(Exception): rl.resolve_current(project_id=exploratory.project_id,run_id=exploratory.run_id)
            with self.assertRaises(Exception): rj.get_approved_projection(project_id=exploratory.project_id,run_id=exploratory.run_id)
            for operation in (lambda:design_service.resolve_current_approved(project_id="wrong",run_id=study.run_id),lambda:rb.resolve_current_accepted(project_id="wrong",run_id=study.run_id,dataset=dataset,codebook=codebook),lambda:rc.resolve_current_approved(project_id="wrong",run_id=study.run_id,dataset=dataset,codebook=codebook,weight_sets=()),lambda:rh.resolve_current_approved(project_id="wrong",run_id=study.run_id,research_question_id="rq1"),lambda:ri.get_approved_projection(project_id="wrong",run_id=study.run_id,objective_id="o1"),lambda:app.quantitative_authority_chain_selection_service.resolve_current_selection(project_id="wrong",run_id=study.run_id),lambda:rl.resolve_current(project_id="wrong",run_id=study.run_id),lambda:rj.get_approved_projection(project_id="wrong",run_id=study.run_id)):
                with self.assertRaises(Exception): operation()
            bounded=(accepted,rd,re_lineage,rf_lineage,rg_lineage,finalized,optional_policy,optional_assessment,study_projection)
            encoded=repr(bounded).lower()
            for forbidden in ("respondent_id","raw_sav","raw_rows","email","phone","address","credentials","provider transcript"): self.assertNotIn(forbidden,encoded)
            corrupt_id=optional_policy.version_id; original_record=state._records[corrupt_id]; state._records[corrupt_id]=replace(original_record,payload_checksum="corrupt")
            try:
                with self.assertRaises(Exception): ui.state.load(corrupt_id,project_id=study.project_id)
            finally: state._records[corrupt_id]=original_record
            app.shutdown()
            restart_llm=_SemanticFake(); restarted=self.container(root,projects,runs,state,restart_llm)
            restarted_design=restarted.quantitative_authority_finalization_service._designs.resolve_current_approved(project_id=study.project_id,run_id=study.run_id)
            restarted_study=restarted.quantitative_study_sufficiency_service.get_approved_projection(project_id=study.project_id,run_id=study.run_id)
            for operation in (lambda:restarted.quantitative_authority_finalization_service.resolve_current(project_id=study.project_id,run_id=study.run_id),lambda:restarted.quantitative_authority_chain_service.reconstruct_forward(manifest_id=finalized.manifest_id,project_id=study.project_id,run_id=study.run_id),lambda:restarted.quantitative_authority_chain_service.reconstruct_backward(manifest_id=finalized.manifest_id,objective_authority_id=ri_refs[0].authority_id,project_id=study.project_id,run_id=study.run_id)):
                with self.assertRaises(Exception): operation()
            self.assertEqual(design.fingerprint,restarted_design.fingerprint); self.assertEqual(study_projection,restarted_study); self.assertEqual(finalized.manifest_fingerprint,restarted.quantitative_authority_chain_service.resolve_exact(manifest_id=finalized.manifest_id,project_id=study.project_id,run_id=study.run_id).manifest_fingerprint); self.assertEqual(0,len(restart_llm.calls))
            self.assertIsNotNone(restarted.quantitative_study_sufficiency_service.repository.get_assessment(study_projection.assessment_version_id,project_id=study.project_id)); self.assertIsNotNone(restarted.quantitative_study_sufficiency_service.repository.get_approval(study_projection.approval_id,project_id=study.project_id)); self.assertIsNotNone(restarted.quantitative_study_sufficiency_service.repository.get_assessment(historical_study_projection.assessment_version_id,project_id=study.project_id))
            delivery_independent=restarted.quantitative_objective_coverage_service._questions.assess(project_id=study.project_id,run_id=study.run_id,design=design,questionnaire_coverage=ra_coverage,data_availability=rb_availability,plan=plan,plan_coverage=rc_coverage,execution_manifest=rd,execution_coverage=rd_coverage,finding_coverage=re_coverage,insight_coverage=None,report_coverage=None,finding_lineage=re_lineage,insight_lineage=None,report_lineage=None,created_at="t70",created_by="system",version_sequence=70)
            delivery_by_rq={x.research_question_id:x for x in delivery_independent}; self.assertIn(delivery_by_rq["rq1"].status,{ResearchQuestionAssessmentStatus.READY_FOR_SUFFICIENCY_REVIEW,ResearchQuestionAssessmentStatus.REQUIRES_METHODOLOGICAL_REVIEW}); self.assertNotEqual(ResearchQuestionAssessmentStatus.BLOCKED,delivery_by_rq["rq-shared"].status)
            qz_restart=restarted.quantitative_authority_finalization_service._designs
            brief_v2=qz_restart.revise_brief(brief.version_id,project_id=study.project_id,run_id=study.run_id,version_id="brief-v2",created_at="t29",created_by="human",title="Revised consumer advocacy and experience")
            brief_v2=qz_restart.submit_brief_for_review(brief_v2.version_id,project_id=study.project_id,run_id=study.run_id,new_version_id="brief-v2-review",actor_id="human",changed_at="t30")
            brief_v2=qz_restart.approve_brief(brief_v2.version_id,project_id=study.project_id,run_id=study.run_id,new_version_id="brief-v2-approved",approval_id="brief-v2-approval",expected_fingerprint=brief_v2.fingerprint,actor_id="human",decided_at="t31",rationale="Approved revised Brief")
            self.assertNotEqual(brief.fingerprint,brief_v2.fingerprint)
            for operation in (lambda:qz_restart.resolve_current_approved(project_id=study.project_id,run_id=study.run_id),lambda:restarted.quantitative_authority_finalization_service.resolve_current(project_id=study.project_id,run_id=study.run_id),lambda:restarted.quantitative_authority_chain_service.reconstruct_forward(manifest_id=finalized.manifest_id,project_id=study.project_id,run_id=study.run_id),lambda:restarted.quantitative_study_sufficiency_service.get_approved_projection(project_id=study.project_id,run_id=study.run_id)):
                with self.assertRaises(Exception): operation()
            self.assertEqual(finalized.manifest_fingerprint,restarted.quantitative_authority_chain_service.resolve_exact(manifest_id=finalized.manifest_id,project_id=study.project_id,run_id=study.run_id).manifest_fingerprint)
            historical_selection=restarted.quantitative_authority_chain_selection_service.load_historical(selection_id=finalized.selection_id,project_id=study.project_id,run_id=study.run_id); self.assertEqual(finalized.selection_fingerprint,historical_selection.fingerprint)
            self.assertIsNotNone(restarted.quantitative_study_sufficiency_service.repository.get_assessment(study_projection.assessment_version_id,project_id=study.project_id)); self.assertIsNotNone(restarted.quantitative_study_sufficiency_service.repository.get_approval(study_projection.approval_id,project_id=study.project_id))
            restarted.shutdown()
            stale_restart=self.container(root,projects,runs,state,_SemanticFake())
            for operation in (lambda:stale_restart.quantitative_authority_finalization_service.resolve_current(project_id=study.project_id,run_id=study.run_id),lambda:stale_restart.quantitative_study_sufficiency_service.get_approved_projection(project_id=study.project_id,run_id=study.run_id)):
                with self.assertRaises(Exception): operation()
            self.assertEqual(finalized.manifest_fingerprint,stale_restart.quantitative_authority_chain_service.resolve_exact(manifest_id=finalized.manifest_id,project_id=study.project_id,run_id=study.run_id).manifest_fingerprint); stale_restart.shutdown()
            fresh=self.container(root,InMemoryProjectRepository(),InMemoryWorkflowRunRepository(),InMemoryQuantitativeStateRepository(),_SemanticFake())
            with self.assertRaises(Exception): fresh.quantitative_study_sufficiency_service.get_approved_projection(project_id=study.project_id,run_id=study.run_id)
            fresh.shutdown(); self.assertEqual(30,len(baseline))

if __name__=="__main__": unittest.main()
