from typing import Protocol


class QuantitativeAuthorityChainRepository(Protocol):
    def save_manifest(self, value): ...
    def get_manifest(self, manifest_id: str, *, project_id: str): ...
    def list_manifests(self, *, project_id: str, run_id: str): ...
