from typing import Protocol

class QuantitativeAuthorityChainSelectionRepository(Protocol):
    def save_selection(self, value): ...
    def get_selection(self, selection_id: str, *, project_id: str): ...
    def list_selections(self, *, project_id: str, run_id: str): ...
