from typing import Protocol
from domain.quantitative.analysis_plan import *

class QuantitativeAnalysisPlanRepository(Protocol):
    def save_plan(self,value:QuantitativeAnalysisPlanVersion,*,run_id:str)->None: ...
    def save_coverage(self,value:QuantitativeAnalysisPlanCoverageManifest,*,run_id:str)->None: ...
    def save_approval(self,value:QuantitativeAnalysisPlanApproval,*,run_id:str)->None: ...
    def save_dataset_only(self,value:DatasetOnlyAnalysisPlanAuthority)->None: ...
    def get_plan(self,version_id:str,*,project_id:str): ...
    def get_coverage(self,manifest_id:str,*,project_id:str): ...
    def get_approval(self,approval_id:str,*,project_id:str): ...
    def list_plans(self,*,project_id:str,run_id:str): ...
