from __future__ import annotations

from typing import Protocol

from domain.quantitative.questionnaire_authority import (
    DatasetOnlyQuestionnaireAuthority, ExpectedMeasurementSchema,
    QuestionnaireDesignCoverageManifest, QuestionnaireValidationManifest,
    QuantitativeQuestionnaireApproval, QuantitativeQuestionnaireVersion,
)


class QuantitativeQuestionnaireRepository(Protocol):
    def save_questionnaire(self, value: QuantitativeQuestionnaireVersion, *, run_id: str) -> None: ...
    def save_approval(self, value: QuantitativeQuestionnaireApproval, *, run_id: str) -> None: ...
    def save_schema(self, value: ExpectedMeasurementSchema, *, run_id: str) -> None: ...
    def save_validation(self, value: QuestionnaireValidationManifest, *, run_id: str) -> None: ...
    def save_coverage(self, value: QuestionnaireDesignCoverageManifest, *, run_id: str) -> None: ...
    def save_dataset_only(self, value: DatasetOnlyQuestionnaireAuthority) -> None: ...
    def get_questionnaire(self, version_id: str, *, project_id: str) -> QuantitativeQuestionnaireVersion | None: ...
    def get_approval(self, approval_id: str, *, project_id: str) -> QuantitativeQuestionnaireApproval | None: ...
    def get_schema(self, schema_id: str, *, project_id: str) -> ExpectedMeasurementSchema | None: ...
    def get_validation(self, manifest_id: str, *, project_id: str) -> QuestionnaireValidationManifest | None: ...
    def get_coverage(self, manifest_id: str, *, project_id: str) -> QuestionnaireDesignCoverageManifest | None: ...
    def get_dataset_only(self, authority_id: str, *, project_id: str) -> DatasetOnlyQuestionnaireAuthority | None: ...
    def list_questionnaires(self, *, project_id: str, run_id: str) -> tuple[QuantitativeQuestionnaireVersion, ...]: ...
