from typing import Protocol

class QuantitativeObjectiveCoverageRepository(Protocol):
    def save_policy(self, value): ...
    def get_policy(self, version_id: str, *, project_id: str): ...
    def list_policies(self, *, project_id: str, run_id: str): ...
    def save_policy_approval(self, value): ...
    def get_policy_approval(self, approval_id: str, *, project_id: str): ...
    def save_assessment(self, value): ...
    def get_assessment(self, version_id: str, *, project_id: str): ...
    def list_assessments(self, *, project_id: str, run_id: str): ...
    def save_approval(self, value): ...
    def get_approval(self, approval_id: str, *, project_id: str): ...
    def save_run_manifest(self, value): ...
    def get_run_manifest(self, manifest_id: str, *, project_id: str): ...
    def save_dataset_only_absence(self, value): ...
