from typing import Protocol

from domain.quantitative.finding_lineage import (
    DatasetOnlyFindingLineageAbsence,
    DesignAwareFindingInputAuthority,
    QuantitativeFindingCoverageManifest,
    QuantitativeFindingDesignLineageManifest,
)


class QuantitativeFindingLineageRepository(Protocol):
    def save_input_authority(self, value: DesignAwareFindingInputAuthority): ...
    def get_input_authority(self, authority_id: str, *, project_id: str): ...
    def save_coverage(self, value: QuantitativeFindingCoverageManifest): ...
    def get_coverage(self, coverage_id: str, *, project_id: str): ...
    def save_manifest(self, value: QuantitativeFindingDesignLineageManifest): ...
    def get_manifest(self, manifest_id: str, *, project_id: str): ...
    def find_manifest_for_input(self, input_authority_id: str, *, project_id: str, run_id: str): ...
    def save_dataset_only_absence(self, value: DatasetOnlyFindingLineageAbsence): ...
