from typing import Protocol
from domain.quantitative.measurement_reconciliation import *
from domain.quantitative.quality import QuestionnaireSnapshot

class QuantitativeMeasurementReconciliationRepository(Protocol):
    def save_reconciliation(self, value: QuantitativeMeasurementReconciliationVersion, *, run_id: str) -> None: ...
    def save_mapping_decision(self, value: ReviewedMeasurementMapping, *, project_id: str, run_id: str) -> None: ...
    def save_approval(self, value: QuantitativeMeasurementReconciliationApproval, *, run_id: str) -> None: ...
    def save_availability(self, value: MeasurementDataAvailabilityManifest, *, run_id: str) -> None: ...
    def save_snapshot(self, value: QuestionnaireSnapshot, *, project_id: str, run_id: str, parent_id: str) -> None: ...
    def save_dataset_only(self, value: DatasetOnlyReconciliationAuthority) -> None: ...
    def get_reconciliation(self, version_id: str, *, project_id: str): ...
    def get_mapping_decision(self, decision_id: str, *, project_id: str): ...
    def get_approval(self, approval_id: str, *, project_id: str): ...
    def get_availability(self, manifest_id: str, *, project_id: str): ...
    def get_snapshot(self, snapshot_id: str, *, project_id: str): ...
    def list_reconciliations(self, *, project_id: str, run_id: str): ...
