from typing import Protocol


class QuantitativeReportLineageRepository(Protocol):
    def save_input_authority(self, value): ...
    def get_input_authority(self, authority_id: str, *, project_id: str): ...
    def save_coverage(self, value): ...
    def get_coverage(self, coverage_id: str, *, project_id: str): ...
    def save_manifest(self, value): ...
    def get_manifest(self, manifest_id: str, *, project_id: str): ...
    def find_manifest_for_input(self, input_authority_id: str, *, project_id: str, run_id: str): ...
    def find_coverage_for_input(self, input_authority_id: str, *, project_id: str, run_id: str): ...
    def save_dataset_only_absence(self, value): ...
    def save_controlled_absence(self, value): ...
    def get_controlled_absence(self, absence_id: str, *, project_id: str): ...
