from typing import Protocol
from domain.quantitative.analysis_execution import *
class QuantitativeAnalysisExecutionRepository(Protocol):
    def save_analysis_outcome(self,value:PlannedAnalysisExecutionOutcome)->PlannedAnalysisExecutionOutcome: ...
    def save_comparison_outcome(self,value:PlannedComparisonExecutionOutcome)->PlannedComparisonExecutionOutcome: ...
    def save_coverage(self,value:AnalysisExecutionCoverageManifest)->AnalysisExecutionCoverageManifest: ...
    def save_manifest(self,value:QuantitativeAnalysisExecutionManifest)->QuantitativeAnalysisExecutionManifest: ...
    def get_analysis_outcome(self,outcome_id:str,*,project_id:str): ...
    def get_comparison_outcome(self,outcome_id:str,*,project_id:str): ...
    def get_coverage(self,coverage_id:str,*,project_id:str): ...
    def get_manifest(self,manifest_id:str,*,project_id:str): ...
