from __future__ import annotations

from typing import Protocol

from domain.quantitative.research_design_authority import (
    DatasetOnlyResearchAuthority,
    QuantitativeResearchDesignApproval,
    QuantitativeResearchDesignVersion,
    QuantitativeStudyBriefVersion,
    QuantitativeTraceabilityManifest,
)

class QuantitativeResearchDesignRepository(Protocol):
    def save_brief(self, value: QuantitativeStudyBriefVersion, *, run_id: str) -> None: ...
    def save_design(self, value: QuantitativeResearchDesignVersion, *, run_id: str) -> None: ...
    def save_approval(self, value: QuantitativeResearchDesignApproval, *, run_id: str) -> None: ...
    def save_manifest(self, value: QuantitativeTraceabilityManifest, *, run_id: str) -> None: ...
    def save_dataset_only(self, value: DatasetOnlyResearchAuthority) -> None: ...
    def get_brief(self, version_id: str, *, project_id: str) -> QuantitativeStudyBriefVersion | None: ...
    def get_design(self, version_id: str, *, project_id: str) -> QuantitativeResearchDesignVersion | None: ...
    def get_approval(self, approval_id: str, *, project_id: str) -> QuantitativeResearchDesignApproval | None: ...
    def get_manifest(self, manifest_id: str, *, project_id: str) -> QuantitativeTraceabilityManifest | None: ...
    def get_dataset_only(self, authority_id: str, *, project_id: str) -> DatasetOnlyResearchAuthority | None: ...
    def list_briefs(self, *, project_id: str, run_id: str) -> tuple[QuantitativeStudyBriefVersion, ...]: ...
    def list_designs(self, *, project_id: str, run_id: str) -> tuple[QuantitativeResearchDesignVersion, ...]: ...
